### ISSUE TITLE
Error: Cannot return null for non-nullable field WorkExperience.status.

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey-backend#709]
Query:
```
query MyPublishes {
  me {
    experiences {
      status
    }
  }
}
```

Headers:
```
  "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTkwNzRmYmVkMTdiNzQxMjc3OWQyM2ZlIiwiaWF0IjoxNTc5MjgxNzYxLCJleHAiOjE1ODE4NzM3NjF9.p7MsKuZIwm9I3GWNsoAl-9SVIYXHT0ZKU9XYyRRwKaY"
```

Response:
```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field WorkExperience.status.",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "me",
        "experiences",
        1,
        "status"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field WorkExperience.status.",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:568:13)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:503:19)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:447:10)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:293:18)",
            "    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:717:10)",
            "    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:707:10)",
            "    at completeAbstractValue (/app/node_modules/graphql/execution/execute.js:664:10)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:593:12)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:565:21)",
            "    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:503:19)",
            "    at /app/node_modules/graphql/execution/execute.js:623:25",
            "    at Array.forEach (<anonymous>)",
            "    at forEach (/app/node_modules/iterall/index.js:83:25)",
            "    at completeListValue (/app/node_modules/graphql/execution/execute.js:619:24)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:581:12)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:565:21)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by peteranny** [comment]
另外這個reponse是status code 200，這樣是預期的嗎？

**Comment by barry800414** [comment]
@peteranny 方便給我該 user 的 id 嗎？
（另外是 production dump 的 data 嗎？

**Comment by peteranny** [comment]
59074fbed17b7412779d23fe
dev環境
